### ISSUE TITLE
本地构建前端项目: npm run build 失败

### ISSUE THREAD

**Issue by uamsunshine** [TencentBlueKing/bk-user#213]
**用文字描述你遇到的问题**

构建saas静态文件报错

**重现方法**
npm  6.9.0
node 12.0.0
npm install   --registry=https://registry.npm.taobao.org
npm run build

running better-npm-run in /root/pages
Executing script: dll

to be executed: babel-node build/build-dll.js
Hash: 1ecceced40baf8796c65
Version: webpack 4.46.0
Time: 1763ms
Built at: 12/21/2021 11:17:55 AM
        Asset     Size  Chunks             Chunk Names
lib.bundle.js  137 KiB       0  [emitted]  lib
Entrypoint lib = lib.bundle.js

  DLL Build complete.

/root/pages/node_modules/depd/index.js:252
  var file = callSite.getFileName() || '<anonymous>'
                      ^

TypeError: callSite.getFileName is not a function
    at callSiteLocation (/root/pages/node_modules/depd/index.js:252:23)
    at depd (/root/pages/node_modules/depd/index.js:111:14)
    at Object.<anonymous> (/root/pages/node_modules/body-parser/index.js:14:32)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Module._compile (/root/pages/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Object.newLoader [as .js] (/root/pages/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! user@1.0.0 build: `better-npm-run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the user@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-21T03_17_59_462Z-debug.log

**预期行为**
 构建成功
**版本**
masterv2.3.2

不是企业版

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**
不是
**额外信息**
没有

**Comment by IMBlues** [comment]
@uamsunshine 

可以尝试升级本地的 Node 和 NPM 版本：
```
npm 6.14.4
node v12.16.2
```

**Comment by IMBlues** [comment]
未得到有效回应，先关闭该 issue。

如果还有其他人有类似问题，欢迎在这里回复，我会重新打开。

**Comment by Xouer** [comment]
你的后端编译成功了吗？
