### ISSUE TITLE
修改或重置用户密码报错：AttributeError: 'list' object has no attribute 'keys'

### ISSUE THREAD

**Issue by RondoChen** [TencentBlueKing/bk-user#276]
**用文字描述你遇到的问题**
重置密码失败
**重现方法**
如图, 在用户管理的前端页面进行重置密码操作时, 操作失败:
![企业微信截图_16448235157607](https://user-images.githubusercontent.com/19532861/154196460-8bb5251d-28cf-4e75-98c0-84a6e943770f.png)
![企业微信截图_20220216122839](https://user-images.githubusercontent.com/19532861/154196499-5b34aad9-4ccb-4367-81ee-3586a6b550ea.png)

后台bk_usermgr.log报错如下:
```
INFO [2022-02-15 17:38:20] bkuser.enhanced_account.middlewares(ln:113): request<_MISSING_> info: Path(/api/v1/login/profile/query/) with QueryString<> via POST from RemoteAddr<192.168.255.109> Agent<python-requests/2.21.0> AcceptLanguage<_MISSING_> Operator<nobody>
INFO [2022-02-15 17:38:20] bkuser.profiles.views(ln:648): going to query username list: ['rondochen2']
INFO [2022-02-15 17:38:20] bkuser.enhanced_account.middlewares(ln:113): request<_MISSING_> info: Path(/api/v2/dynamic_fields/) with QueryString<no_page=True> via GET from RemoteAddr<192.168.255.104> Agent<Swagger-Codegen/0.1.4/python> AcceptLanguage<zh-hans> Operator<rondochen2>
INFO [2022-02-15 17:38:20] bkuser.enhanced_account.middlewares(ln:113): request<_MISSING_> info: Path(/api/v2/profiles/7/) with QueryString<lookup_field=id> via PATCH from RemoteAddr<192.168.255.104> Agent<Swagger-Codegen/0.1.4/python> AcceptLanguage<zh-hans> Operator<rondochen2>
ERROR [2022-02-15 17:38:20] bkuser.profiles.views(ln:320): failed to update profile
Traceback (most recent call last):
  File "/data/bkee/usermgr/api/bkuser/profiles/views.py", line 318, in _update
  File "/data/bkee/usermgr/api/bkuser/profiles/models.py", line 134, in save
  File "/data/bkee/usermgr/api/bkuser/profiles/models.py", line 131, in custom_validate
  File "/data/bkee/usermgr/api/bkuser/profiles/validators.py", line 32, in validate_extras_value_unique
AttributeError: 'list' object has no attribute 'keys'
INFO [2022-02-15 17:38:20] bkuser.common.cache(ln:20): going to clear cache default
ERROR [2022-02-15 17:38:20] django.request(ln:135): Internal Server Error: /api/v2/profiles/7/
Traceback (most recent call last):
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/rest_framework/views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/rest_framework/views.py", line 422, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'bkuser.common.error_codes.CoreAPIError'>`
```

**版本**
- 用户管理版本: 2.2.6-fix2

**如果是 SaaS 页面问题，请提供使用的操作系统和浏览器信息**
 - OS: win10
 - Browser chrome

**额外信息**
曾经进行过用户管理1.0迁移到2.0, 怀疑是旧数据和新版本程序不匹配导致

**Comment by IMBlues** [comment]
# 主要的问题是需要批量刷新 1.0 遗留的旧数据。

## 操作方法：

### 进入执行后台

如果部署方式是二进制后台部署，那么需要登录到对应的机器节点，并执行：
```bash
workon usermgr-api
# 当版本小于 2.3.x 时（例如 2.2.x），需要额外执行
export DJANGO_SETTINGS_MODULE=config.ee.prod
```

如果是容器化方式部署，直接通过 `kubectl exec -it bk-user-api-web-{random} bash` 进入容器即可

### 执行数据刷新指令

```bash
# dry_run 运行，会将预期更新打印在日志中
python manage.py update_profile_extras --dry_run --verbose
```

可以在 `/data/bkee/logs/usermgr/` 中查看对应日志，观测日志输出，会将更新概况打印出来，判断更新内容无误后，可以执行
```bash
python manage.py update_profile_extras --verbose
```

执行成功后观察是否还会有对应问题出现。

**Comment by RondoChen** [comment]
问题已修复~感谢
