### ISSUE TITLE
日志配置优化

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-user#295]
1. 本地开发, all into stdout
2. 容器化调试, helm charts values支持, all into stdout
3. 容器化正式, split into different files, with bklogconfig
4. v3及内部版, all into stdout(保持现状)

**Comment by IMBlues** [comment]
1. 本身已经支持，[get_logging 函数](https://github.com/TencentBlueKing/bk-user/blob/057f270d66a1834312306c9fba1f4e95521f10b1/src/bkuser_global/logging.py#L23) 传入 STDOUT 类型即可
2. 同上
3. 可以考虑拆分，进一步扩展 get_logging 函数？

**Comment by wklken** [comment]
上云切换到结构化, 多个文件

**Comment by wklken** [comment]
- celery日志: worker和beat目前
- MySQL 日志: 确定有没有
- 其他: 500报错/调用外部组件报错的堆栈, 需要精准, 要么stdout一份+文件一份

**Comment by wklken** [comment]
```
bkuser_shell.common.exception_handler ERROR request apiServer failed: 
Traceback (most recent call last):
  File "/root/.pyenv/versions/bk-user/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/workspace/tx/wklken/bk-user/src/saas/bkuser_global/drf_crown/crown.py", line 210, in decorated
    original_data = func(*args, **kwargs, **in_content)
  File "/root/workspace/tx/wklken/bk-user/src/saas/bkuser_shell/organization/views/departments.py", line 131, in list
    all_categories = self.get_paging_results(no_auth_categories_api_instance.v2_categories_list)
  File "/root/workspace/tx/wklken/bk-user/src/saas/bkuser_shell/apis/viewset.py", line 115, in get_paging_results
    first_results = list_func(page_size=page_size, ordering="id", **kwargs)
  File "/root/workspace/tx/wklken/bk-user/src/saas/bkuser_sdk/api/categories_api.py", line 475, in v2_categories_list
    (data) = self.v2_categories_list_with_http_info(**kwargs)  # noqa: E501
  File "/root/workspace/tx/wklken/bk-user/src/saas/bkuser_sdk/api/categories_api.py", line 588, in v2_categories_list_with_http_info
    collection_formats=collection_formats)
  File "/root/workspace/tx/wklken/bk-user/src/saas/bkuser_sdk/api_client.py", line 346, in call_api
    _request_timeout,
  File "/root/workspace/tx/wklken/bk-user/src/saas/bkuser_sdk/api_client.py", line 159, in __call_api
    _request_timeout=_request_timeout,
  File "/root/workspace/tx/wklken/bk-user/src/saas/bkuser_sdk/api_client.py", line 388, in request
    headers=headers,
  File "/root/workspace/tx/wklken/bk-user/src/saas/bkuser_sdk/rest.py", line 237, in GET
    query_params=query_params)
  File "/root/workspace/tx/wklken/bk-user/src/saas/bkuser_sdk/rest.py", line 227, in request
    raise ApiException(http_resp=r)
bkuser_sdk.rest.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 12 Apr 2022 07:53:49 GMT', 'Server': 'WSGIServer/0.2 CPython/3.6.15', 'Content-Type': 'text/html', 'Vary': 'Accept-Language, Cookie', 'Content-Language': 'zh-hans', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'same-origin', 'X-Frame-Options': 'DENY', 'Content-Length': '145'})
HTTP response body: 
<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>


==== response {'result': False, 'data': None, 'code': -1, 'message': 'API 服务返回异常，请检查 API 服务日志'} 200
```

目前saas是没有办法知道是哪个url报错然后去追踪的, 只能去看代码 => 非常影响问题排查效率
