### ISSUE TITLE
同步LDAP用户报错，LDAP组织架构类是指什么？

### ISSUE THREAD

**Issue by hlilhuang** [TencentBlueKing/bk-user#375]
第一个问题：同步LDAP用户时报错，报错日志如下：
ldap3.core.exceptions.LDAPAttributeError: invalid attribute type memberOf

 ldap3.core.exceptions.LDAPAttributeError: invalid attribute type memberOf
  File "/data/bkce/usermgr/api/bkuser/categories/vendors/ldap/adapter.py", line 291, in _fetch_data
bkuser.categories.exceptions.FetchDataFromRemoteFailed: 无法获取用户数据, 请检查配置

第二个问题：LDAP中组织架构类字段是指什么？
![企业微信截图_16503529102536](https://user-images.githubusercontent.com/93375471/163977909-0059ff07-b5f0-47f0-b9f9-be0f5c0be87f.png)

**Comment by IMBlues** [comment]
可以参考 #143 手动修改
也可以参考 #182 做出的修改，在产品上不填写 memberOf 字段即可

**Comment by ilovedj2022** [comment]
> 可以参考 #143 手动修改 也可以参考 #182 做出的修改，在产品上不填写 memberOf 字段即可

社区版6.0.5的版本，“在产品上不填写 memberOf 字段即可”具体怎么操作？

**Comment by IMBlues** [comment]
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/4225292/164188570-7c6c9897-e9a5-4ab4-9883-abed1920dcf8.png">

如果升级到了最新版，这里用户组关联字段是可以不填写的，留空即不同步用户组数据

**Comment by ilovedj2022** [comment]
ldap版本
slapd -V
@(#) $OpenLDAP: slapd 2.4.40 (Mar 22 2017 06:29:21) $

**Comment by ilovedj2022** [comment]
组织架构类，这里指的什么，其它工具接ldap都没有要求填组织架构类，也可以正常接入；

**Comment by ilovedj2022** [comment]
![image](https://user-images.githubusercontent.com/104056344/164204343-751acd45-7a41-42fe-8784-894ad88ab102.png)
![image](https://user-images.githubusercontent.com/104056344/164204909-9e11f585-31f1-46ef-9df5-94c97c22150b.png)
 
图中2个项目配置是目前可以正常接入ldap

**Comment by IMBlues** [comment]
说白一点，你需要告诉用户管理，哪一个类是代表部门的，不然没法同步组织架构。。。

> 组织架构类，这里指的什么，其它工具接ldap都没有要求填组织架构类，也可以正常接入；

**Comment by ilovedj2022** [comment]
search_filter='(objectClass=organizationalUnit)',测试用这个filter去拉取可以拉到一级部门的OU，拉不到二级部门的OU

**Comment by ilovedj2022** [comment]
dn里加上一级部门OU也能拉到二级部门

**Comment by ilovedj2022** [comment]
INFO [2022-04-21 14:34:49] bkuser.categories.tasks(ln:16): going to sync Category<2>
INFO [2022-04-21 14:34:49] bkuser.categories.vendors.ldap.client(ln:75): going to search (objectClass=organizationalUnit) from dc=gostart,dc=com
INFO [2022-04-21 14:34:49] bkuser.categories.vendors.ldap.client(ln:75): going to search (objectClass=organizationalUnit) from dc=gostart,dc=com
INFO [2022-04-21 14:34:49] bkuser.categories.vendors.ldap.client(ln:75): going to search (objectClass=inetOrgPerson) from dc=gostart,dc=com
ERROR [2022-04-21 14:34:49] bkuser.categories.vendors.ldap.adapter(ln:290): failed to get users from remote server
Traceback (most recent call last):
  File "/data/bkce/usermgr/api/bkuser/categories/vendors/ldap/adapter.py", line 287, in _fetch_data
  File "/data/bkce/usermgr/api/bkuser/categories/vendors/ldap/client.py", line 82, in search
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/ldap3/extend/__init__.py", line 125, in paged_search
    paged_criticality)
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/ldap3/extend/standard/PagedSearch.py", line 139, in paged_search_accumulator
    paged_criticality):
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/ldap3/extend/standard/PagedSearch.py", line 68, in paged_search_generator
    None if cookie is True else cookie)
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/ldap3/core/connection.py", line 772, in search
    raise LDAPAttributeError('invalid attribute type ' + attribute_name_to_check)
ldap3.core.exceptions.LDAPAttributeError: invalid attribute type memberOf
