### ISSUE TITLE
list_user接口：page参数超过用户数量出现返回异常

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-user#595]
**问题详细描述**
- 调用用户管理list_user接口时，如果page参数传递超过用户数量的值，接口会返回404，而不是空或者没有数据的相关提示，比较容易误导开发者：
- 异常返回图示：
![image](https://user-images.githubusercontent.com/90179140/181449462-7b4dcf3f-e382-45e4-bc15-ee9e5621c708.png)

**版本**
- 现有的最新版本仍然存在该问题

**Comment by wklken** [comment]
drf pagination默认的做法, 如果要处理, 需要改`StandardResultsSetPagination` => 但是, 返回结果中count必须保持正确(比较复杂)

```
ERROR [2022-09-27 14:35:42,573] unknown exception while handling the request, detail={'error': 'unknown', 'path': '/api/v2/profiles/', 'method': 'GET', 'query_params': <QueryDict: {'page': ['2'], 'page_size': ['100']}>, 'request_id': None}
Traceback (most recent call last):
  File "/root/.pyenv/versions/bk-user/lib/python3.6/site-packages/rest_framework/pagination.py", line 204, in paginate_queryset
    self.page = paginator.page(page_number)
  File "/root/.pyenv/versions/bk-user/lib/python3.6/site-packages/django/core/paginator.py", line 76, in page
    number = self.validate_number(number)
  File "/root/.pyenv/versions/bk-user/lib/python3.6/site-packages/django/core/paginator.py", line 58, in validate_number
    raise EmptyPage(_('That page contains no results'))
django.core.paginator.EmptyPage: 本页结果为空

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/bk-user/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/.pyenv/versions/bk-user/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/.pyenv/versions/bk-user/lib/python3.6/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/root/workspace/tx/wklken/bk-user/src/api/bkuser_core/profiles/v2/views.py", line 198, in list
    page = self.paginate_queryset(queryset)
  File "/root/.pyenv/versions/bk-user/lib/python3.6/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/root/workspace/tx/wklken/bk-user/src/api/bkuser_core/apis/v2/viewset.py", line 49, in paginate_queryset
    return super().paginate_queryset(queryset, request, view)
  File "/root/.pyenv/versions/bk-user/lib/python3.6/site-packages/rest_framework/pagination.py", line 209, in paginate_queryset
    raise NotFound(msg)
rest_framework.exceptions.NotFound: 无效页面。
```

**Comment by wklken** [comment]
https://stackoverflow.com/questions/31251036/404-when-page-number-is-too-high

**Comment by wklken** [comment]
降低优先级, 优先看下`/api/v3`中能处理这种场景, `/api/v2`暂不处理

**Comment by Canway-shiisa** [comment]
list_department同样存在问题
