### ISSUE TITLE
无权限用户申请权限后查看部门下用户详情报错

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-user#657]
```
Traceback (most recent call last):
  File "/cache/.bk/env/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "./bkuser_global/drf_crown/crown.py", line 210, in decorated
  File "./bkuser_shell/organization/views/profiles.py", line 148, in list
  File "./bkuser_sdk/api/profiles_api.py", line 634, in v2_profiles_list
  File "./bkuser_sdk/api/profiles_api.py", line 747, in v2_profiles_list_with_http_info
  File "./bkuser_sdk/api_client.py", line 346, in call_api
  File "./bkuser_sdk/api_client.py", line 159, in __call_api
  File "./bkuser_sdk/api_client.py", line 388, in request
  File "./bkuser_sdk/rest.py", line 237, in GET
  File "./bkuser_sdk/rest.py", line 227, in request
bkuser_sdk.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Server': 'gunicorn/19.9.0', 'Date': 'Fri, 02 Sep 2022 03:36:14 GMT', 'Connection': 'keep-alive', 'Content-Type': 'application/json', 'Allow': 'GET, POST, HEAD, OPTIONS', 'Vary': 'Accept-Language, Cookie', 'Content-Language': 'zh-hans', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'same-origin', 'X-Frame-Options': 'DENY', 'Content-Length': '71', 'X-Request-Id': 'd081373971044b4c80db9800e51b4833'})
HTTP response body: {"code":"QUERY_PARAMS_ERROR","detail":"查询参数错误，请检查"}
```

backend

```
ERROR [2022-09-02 11:43:43] 197 list 6045 140285400848712
failed to query profiles
Traceback (most recent call last):
  File "/data/bkce/usermgr/api/bkuser_core/profiles/v2/views.py", line 195, in list
  File "/data/bkce/usermgr/api/bkuser_core/apis/v2/viewset.py", line 233, in filter_queryset
  File "/data/bkce/usermgr/api/bkuser_core/bkiam/filters.py", line 54, in filter_queryset
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1438, in _add_q
    split_subq=split_subq, check_filterable=check_filterable,
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1295, in build_filter
    check_filterable=check_filterable,
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1438, in _add_q
    split_subq=split_subq, check_filterable=check_filterable,
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1309, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1135, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1563, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'department._bk_iam_path_' into field. Choices are: account_expiration_date, category_id, code, country_code, create_time, departments, display_name, domain, email, enabled, expirationnoticerecord, extras, id, iso_code, language, leader, login, logo, password, password_update_time, password_valid_days, position, qq, resetpassword, role, staff_status, status, subordinate_staff, telephone, time_zone, tokens, type, update_time, username, wx_openid, wx_userid
```

**Comment by wklken** [comment]
the iam query

```
request: [method=`POST`, url=`http://bkiam.service.consul:5001/api/v1/policy/query`, data=`{'system': 'bk_usermgr', 'subject': {'type': 'user', 'id': '15tian6@mm12345.com'}, 'action': {'id': 'view_department'}, 'resources': [], 'environment': {}}`] response: [status_code=`200`, request_id=`32c6b1afedf441e5823c1738efb9324c`, content=`b'{"code":0,"message":"ok","data":{"field":"department._bk_iam_path_","op":"starts_with","value":"/category,72/"}}'`]
```
