### ISSUE TITLE
login response handle 

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-user#662]
```
ERROR [2022-09-07 10:42:13] 230 log_response 38 139827594598984 
Internal Server Error: / 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/app/bklogin/bkauth/decorators.py", line 21, in wrapped_view
    return view_func(*args, **kwargs)
  File "/app/bklogin/common/mixins/exempt.py", line 27, in dispatch
    return super(LoginExemptMixin, self).dispatch(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/bklogin/bkauth/views.py", line 46, in wrapped_view
    origin_url = resp._request.META.get("HTTP_REFERER")
AttributeError: 'HttpResponse' object has no attribute '_request'
```

**Comment by wklken** [comment]
重构版已处理

**Comment by wklken** [comment]
2.5.x
