### ISSUE TITLE
excel 导入 username为全数字报错

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-user#673]
```
>>> print(a["message"])
同步用户解析字段 <username> 失败: 4019814 不符合格式要求. [user_raw_info=(4019814, '', '', , '正常', '在职', '总公司/demo功能体验', None, None, None, None, None)]
>>> print(a["exc_info"])
Traceback (most recent call last):
  File "/app/bkuser_core/categories/plugins/local/parsers.py", line 179, in parse
    validate_username(value=raw_content)
  File "/app/bkuser_core/profiles/validators.py", line 29, in validate_username
    if not re.fullmatch(re.compile(USERNAME_REGEX), value):
  File "/usr/local/lib/python3.6/re.py", line 177, in fullmatch
    return _compile(pattern, flags).fullmatch(string)
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bkuser_core/categories/plugins/local/syncer.py", line 163, in _sync_users
    profile_params = parser_set.parse_row(user_raw_info, skip_keys=["department_name", "leader"])
  File "/app/bkuser_core/categories/plugins/local/syncer.py", line 328, in parse_row
    params.update(self.parse_key(f_name, row_data_list))
  File "/app/bkuser_core/categories/plugins/local/syncer.py", line 340, in parse_key
    return _pa.parse(cell_data)
  File "/app/bkuser_core/categories/plugins/local/parsers.py", line 182, in parse
    raise ParseFailedException(field_name=self.name, reason=_("{} 不符合格式要求").format(raw_content))
bkuser_core.categories.plugins.local.exceptions.ParseFailedException: 解析字段 username 失败: 4019814 不符合格式要求
```

**Comment by wklken** [comment]
重构版中解决问题
