### ISSUE TITLE
[bug] 2.5.0 SaaS 权限报错

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-user#762]
```
{
    "levelname": "ERROR",
    "asctime": "2022-10-26 16:45:22,123",
    "pathname": "/app/bkuser_core/common/exception_handler.py",
    "lineno": 94,
    "funcName": "get_ee_exception_response",
    "process": 422,
    "thread": 140149326157640,
    "request_id": "d6ccd449ad2ca27f1c11257e60a942cb",
    "message": "unknown exception while handling the request, detail={'error': 'unknown', 'path': '/api/v1/web/home/tree/', 'method': 'GET', 'query_params': <QueryDict: {'only_enabled': ['false']}>, 'request_id': 'd6ccd449ad2ca27f1c11257e60a942cb'}",
    "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/site-packages/rest_framework/views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n  File \"/app/bkuser_core/api/web/home/views.py\", line 155, in get\n    for department in self._list_department_tops(operator):\n  File \"/app/bkuser_core/api/web/home/views.py\", line 74, in _list_department_tops\n    queryset = Department.objects.filter(enabled=True).filter(dept_ft)\n  File \"/usr/local/lib/python3.6/site-packages/django/db/models/query.py\", line 941, in filter\n    return self._filter_or_exclude(False, args, kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/django/db/models/query.py\", line 961, in _filter_or_exclude\n    clone._filter_or_exclude_inplace(negate, args, kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/django/db/models/query.py\", line 968, in _filter_or_exclude_inplace\n    self._query.add_q(Q(*args, **kwargs))\n  File \"/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py\", line 1416, in add_q\n    clause, _ = self._add_q(q_object, self.used_aliases)\n  File \"/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py\", line 1438, in _add_q\n    split_subq=split_subq, check_filterable=check_filterable,\n  File \"/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py\", line 1295, in build_filter\n    check_filterable=check_filterable,\n  File \"/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py\", line 1438, in _add_q\n    split_subq=split_subq, check_filterable=check_filterable,\n  File \"/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py\", line 1309, in build_filter\n    lookups, parts, reffed_expression = self.solve_lookup_type(arg)\n  File \"/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py\", line 1135, in solve_lookup_type\n    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())\n  File \"/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py\", line 1563, in names_to_path\n    \"Choices are: %s\" % (name, \", \".join(available)))\ndjango.core.exceptions.FieldError: Cannot resolve keyword 'department._bk_iam_path_' into field. Choices are: category_id, children, code, create_time, enabled, extras, id, level, lft, name, order, parent, parent_id, profiles, rght, tree_id, update_time"
}
```

**Comment by wklken** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/app/bkuser_core/api/web/home/views.py", line 155, in get
    for department in self._list_department_tops(operator):
  File "/app/bkuser_core/api/web/home/views.py", line 74, in _list_department_tops
    queryset = Department.objects.filter(enabled=True).filter(dept_ft)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1438, in _add_q
    split_subq=split_subq, check_filterable=check_filterable,
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1295, in build_filter
    check_filterable=check_filterable,
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1438, in _add_q
    split_subq=split_subq, check_filterable=check_filterable,
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1309, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1135, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1563, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'department._bk_iam_path_' into field. Choices are: category_id, children, code, create_time, enabled, extras, id, level, lft, name, order, parent, parent_id, profiles, rght, tree_id, update_time
```

**Comment by wklken** [comment]
https://github.com/TencentBlueKing/bk-user/pull/764
