### ISSUE TITLE
mad目录新建异常

### ISSUE THREAD

**Issue by Canway-shiisa** [TencentBlueKing/bk-user#777]
**重现方法**
新建mad目录 -> 填错或者空掉部分必填选项 -> 点击<下一步>触发异常 -> 更正错误的配置后再次点击<下一步> -> 出现<无法创建配置>的异常提示
=》
- 首次填写错误配置后点击<下一步>：
![image](https://user-images.githubusercontent.com/90179140/199656764-1f667b6d-f992-4ae8-81cd-89367b114148.png)

接口调用：
![image](https://user-images.githubusercontent.com/90179140/199657487-e7e7de89-1415-4763-9e75-f881fb883df0.png)

接口返回：
![image](https://user-images.githubusercontent.com/90179140/199657519-a027add9-46ea-4356-bda9-57df2d77a83f.png)

相关日志：
![image](https://user-images.githubusercontent.com/90179140/199657000-0f9f7b4a-98b0-4763-8081-4feaa1c4c111.png)

- 将错误配置更改后重新点击 <下一步>：
<img width="952" alt="Snipaste_2022-11-03_14-09-39" src="https://user-images.githubusercontent.com/90179140/199657332-0be25b7a-ca2f-4a80-b474-13760c1df798.png">

接口调用：
![image](https://user-images.githubusercontent.com/90179140/199657412-71f41938-362a-480d-bbb2-9c0be64d2d9d.png)

接口返回：
![image](https://user-images.githubusercontent.com/90179140/199657436-3a140c72-b2d7-4857-a5fb-d97d008bd166.png)

相关日志：
![image](https://user-images.githubusercontent.com/90179140/199657357-74117ac4-4bc0-4680-aae2-df7497be18d9.png)

**预期行为**
配置填写过程中应该调用更新接口，更新配置，不该新建配置导致冲突

**版本**
用户管理2.5.0-beta1
github开源版本

**其他**
异常日志文本：
1.首次点击<下一步>
INFO [2022-11-03 14:19:37] 110 _http_request 10606 139625494383688 
request: [method=`POST`, url=`http://bkiam.service.consul:5001/api/v1/policy/query`, data=`{'system': 'bk_usermgr', 'subject': {'type': 'user', 'id': 'admin'}, 'action': {'id': 'manage_category'}, 'resources': [], 'environment': {}}`] response: [status_code=`200`, request_id=`9a00cd4525bd49e48865dcbd342d344e`, content=`b'{"code":0,"message":"ok","data":{"field":"","op":"any","value":[]}}'`] 

INFO [2022-11-03 14:19:37] 86 create_general_log 10606 139625494383688 
Operator<admin> update object<connection-default-user_member_of> of Setting 

INFO [2022-11-03 14:19:37] 98 update_sync_tasks 10606 139625494383688 
going to update periodic task for Category<5>, the category type is mad 

INFO [2022-11-03 14:19:37] 86 create_general_log 10606 139625494383688 
Operator<admin> update object<connection-default-password> of Setting 

INFO [2022-11-03 14:19:37] 98 update_sync_tasks 10606 139625494383688 
going to update periodic task for Category<5>, the category type is mad 

INFO [2022-11-03 14:19:37] 86 create_general_log 10606 139625494383688 
Operator<admin> update object<connection-default-user> of Setting 

INFO [2022-11-03 14:19:37] 98 update_sync_tasks 10606 139625494383688 
going to update periodic task for Category<5>, the category type is mad 

INFO [2022-11-03 14:19:37] 86 create_general_log 10606 139625494383688 
Operator<admin> update object<connection-default-base_dn> of Setting 

INFO [2022-11-03 14:19:37] 98 update_sync_tasks 10606 139625494383688 
going to update periodic task for Category<5>, the category type is mad 

INFO [2022-11-03 14:19:37] 86 create_general_log 10606 139625494383688 
Operator<admin> update object<connection-default-pull_cycle> of Setting 

INFO [2022-11-03 14:19:37] 98 update_sync_tasks 10606 139625494383688 
going to update periodic task for Category<5>, the category type is mad 

ERROR [2022-11-03 14:19:37] 94 get_ee_exception_response 10606 139625494383688 
unknown exception while handling the request, detail={'error': 'unknown', 'path': '/api/v1/web/categories/5/settings/namespaces/connection/', 'method': 'POST', 'query_params': <QueryDict: {}>, 'request_id': '3ae0db2a9dec4ca3aa26f9763b1975a8'} 
Traceback (most recent call last):
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/data/bkee/usermgr/api/bkuser_core/api/web/category/views.py", line 168, in post
    extra_values={"request": request},
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 182, in send
    for receiver in self._live_receivers(sender)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 182, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/data/bkee/usermgr/api/bkuser_core/categories/plugins/ldap/handlers.py", line 100, in update_sync_tasks
    update_or_create_sync_tasks(instance, operator)
  File "/data/bkee/usermgr/api/bkuser_core/categories/plugins/ldap/handlers.py", line 51, in update_or_create_sync_tasks
    elif cycle_value < min_sync_period:
TypeError: '<' not supported between instances of 'int' and 'NoneType'

2.二次点击<下一步>
INFO [2022-11-03 14:18:51] 110 _http_request 10583 139625358281800 
request: [method=`POST`, url=`http://bkiam.service.consul:5001/api/v1/policy/query`, data=`{'system': 'bk_usermgr', 'subject': {'type': 'user', 'id': 'admin'}, 'action': {'id': 'manage_category'}, 'resources': [], 'environment': {}}`] response: [status_code=`200`, request_id=`e6fe9ed9204246d09208b4db15e22a36`, content=`b'{"code":0,"message":"ok","data":{"field":"","op":"any","value":[]}}'`] 

INFO [2022-11-03 14:18:51] 86 create_general_log 10583 139625358281800 
Operator<admin> update object<connection-default-user_member_of> of Setting 

INFO [2022-11-03 14:18:51] 98 update_sync_tasks 10583 139625358281800 
going to update periodic task for Category<5>, the category type is mad 

INFO [2022-11-03 14:18:51] 86 create_general_log 10583 139625358281800 
Operator<admin> update object<connection-default-password> of Setting 

INFO [2022-11-03 14:18:51] 98 update_sync_tasks 10583 139625358281800 
going to update periodic task for Category<5>, the category type is mad 

INFO [2022-11-03 14:18:51] 86 create_general_log 10583 139625358281800 
Operator<admin> update object<connection-default-user> of Setting 

INFO [2022-11-03 14:18:51] 98 update_sync_tasks 10583 139625358281800 
going to update periodic task for Category<5>, the category type is mad 

ERROR [2022-11-03 14:18:51] 151 post 10583 139625358281800 
cannot create setting. [meta=user_member_of-connection-mad, value=dc=a,dc=b, category=Category-5-ad] 
Traceback (most recent call last):
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/query.py", line 437, in get
    self.model._meta.object_name
bkuser_core.user_settings.models.Setting.DoesNotExist: Setting matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '5-17' for key 'user_settings_setting_category_id_meta_id_bc909709_uniq'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/bkee/usermgr/api/bkuser_core/api/web/category/views.py", line 147, in post
    meta=meta, value=setting["value"], category=category
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/query.py", line 608, in update_or_create
    obj, created = self.select_for_update().get_or_create(defaults, **kwargs)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/query.py", line 588, in get_or_create
    return self.create(**params), True
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/base.py", line 740, in save
    force_update=force_update, update_fields=update_fields)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/base.py", line 778, in save_base
    force_update, using, update_fields,
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/base.py", line 921, in _do_insert
    using=using, raw=raw,
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/data/bkee/.envs/usermgr-api/lib/python3.6/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1062, "Duplicate entry '5-17' for key 'user_settings_setting_category_id_meta_id_bc909709_uniq'")

**Comment by wklken** [comment]
等待 v2.5.0-beta.4
