### ISSUE TITLE
同步ad域账号数据失败

### ISSUE THREAD

**Issue by shitangjiejie08** [TencentBlueKing/bk-user#841]
**用文字描述你遇到的问题**

Microsoft Active Directory同步用户数据失败，提示”同步数据失败, 无法获取用户数据, 请检查配置“
登录服务器查看work.log日志，报错信息如下，提示邮箱字段不正确：
`[2022-12-12 17:06:05,392: ERROR/ForkPoolWorker-1] Task bkuser.categories.tasks.adapter_sync[913f881a-9d60-4a31-a5fc-c8865014791a] raised unexpected: FetchDataFromRemoteFailed('无法获取用户数据, 请检查配置',)
Traceback (most recent call last):
  File "/data/bkce/usermgr/api/bkuser/categories/vendors/ldap/adapter.py", line 287, in _fetch_data
  File "/data/bkce/usermgr/api/bkuser/categories/vendors/ldap/client.py", line 82, in search
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/ldap3/extend/__init__.py", line 125, in paged_search
    paged_criticality)
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/ldap3/extend/standard/PagedSearch.py", line 139, in paged_search_accumulator
    paged_criticality):
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/ldap3/extend/standard/PagedSearch.py", line 68, in paged_search_generator
    None if cookie is True else cookie)
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/ldap3/core/connection.py", line 772, in search
    raise LDAPAttributeError('invalid attribute type ' + attribute_name_to_check)
ldap3.core.exceptions.LDAPAttributeError: invalid attribute type email

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/data/bkce/.envs/usermgr-api/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data/bkce/usermgr/api/bkuser/categories/tasks.py", line 31, in adapter_sync
  File "/data/bkce/usermgr/api/bkuser/categories/vendors/base.py", line 155, in raw2db
  File "/data/bkce/usermgr/api/bkuser/categories/vendors/ldap/adapter.py", line 251, in fetch_and_sync
  File "/data/bkce/usermgr/api/bkuser/categories/vendors/ldap/adapter.py", line 291, in _fetch_data
bkuser.categories.exceptions.FetchDataFromRemoteFailed: 无法获取用户数据, 请检查配置`

请问这个邮件字段应该填什么啊 
![image](https://user-images.githubusercontent.com/22259794/207205581-3867f080-008f-4a49-86ee-9b95e63308f0.png)

**Comment by wklken** [comment]
试下`mail`? 

相关资料:
- 所有ldap/mad相关问题会在 https://github.com/TencentBlueKing/bk-user/issues/429
- 问答社区: 用户管理LDAP,AD同步FQA https://bk.tencent.com/s-mart/community/question/1901
